// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaPonto.Data;

#nullable disable

namespace SistemaPonto.Migrations
{
    [DbContext(typeof(PontoDbContext))]
    partial class PontoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("SistemaPonto.Models.PontoModels", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idColaborador")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Apontamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
